version: 0.75.{build}
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
platform: x86
clone_depth: 1
build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\WINDOWS

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"

    nmake -f MAKEFILE.NG clean

    nmake -f MAKEFILE.NG VER="/DNG_VER_MAJOR=0 /DNG_VER_MINOR=0 /DNG_VER_BUILD=0 /DNG_VER_REVISION=0"
test: off
artifacts:
- path: WINDOWS\puttyng.exe
  name: puttyng.exe
deploy: off